// generateEntryReviewFixtures.mjs
//
// Regenerates app/src/fixtures/entryReview*.json by calling the REAL
// getEntryReview handler against a real Postgres, which is what app/README.md
// means by "real fixture data - generated by calling the actual tested handler".
//
// Committed rather than run ad hoc because the fixtures now have to cover four
// distinct citation states, and hand-editing JSON to fake them would quietly
// destroy the one property that makes them worth having: that a fixture is
// something the handler actually produced, not something someone believed it
// would produce.
//
// The four states, which are the four shapes the entry screen has to render:
//
//   cited + spelling matches   the common case. One affirmation, no false choice.
//   cited + spelling differs   a correction is on offer.
//   uncited + tone mismatch    a word predating citations; curator territory.
//   uncited + ambiguous        one spelling, several etymologies - the `kọ́` case.
//
// Everything it creates is namespaced and removed afterwards, so it is safe to
// run against a dev database. Requires DATABASE_URL and `npm run build:api`.
//
// The display texts are invented but ORTHOGRAPHICALLY REAL Yoruba - only letters the
// syllabifier models, and verified absent from the corpus so they cannot collide with
// a genuine entry. They cannot be namespaced like the word_ids are: `fixturegen_adìyẹ`
// contains an underscore, the syllabifier drops characters it does not model, and
// syllabifySpans then refuses the word entirely - so every fixture would exercise the
// cannot-be-edited fallback instead of the tone editor. Isolation comes from the
// word_id and entry_id prefixes, which is what cleanup keys on anyway.

import { writeFileSync } from 'node:fs';
import path from 'node:path';
import pg from 'pg';
import { orthographyInsensitiveForm } from '@yoruba-student-dict-platform/shared';
import { getEntryReview } from '../api/dist/handlers/getEntryReview.js';

const NS = 'fixturegenentry_';
const ENTRY_NS = 'fixturegenentry-etym-';
const FIXTURES_DIR = path.join(import.meta.dirname, '..', 'app', 'src', 'fixtures');

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('DATABASE_URL is not set.');
  process.exit(1);
}
const pool = new pg.Pool({ connectionString });

async function cleanup() {
  await pool.query('delete from upstream_citations where word_id like $1', [`${NS}%`]);
  await pool.query('delete from golden_record where word_id like $1', [`${NS}%`]);
  await pool.query('delete from users where email like $1', [`${NS}%`]);
  await pool.query('delete from kaikki_senses where entry_id like $1', [`${ENTRY_NS}%`]);
}

async function addSense({ entryId, form, pos, etymologyNumber, glosses, standardForms }) {
  await pool.query(
    `insert into kaikki_senses
       (entry_id, pos, etymology_number, etymology_text, headword, canonical_value,
        canonical_inference_method, canonical_confidence, canonical_original_value,
        standard_forms, glosses, alt_of_targets)
     values ($1, $2, $3, $4, $5, $6, 'explicit_canonical_tag', 1.0, $6, $7, $8, '{}')`,
    [entryId, pos, etymologyNumber, 'Inherited from Proto-Yoruboid.', form, form, standardForms ?? [form], glosses],
  );
  await pool.query(
    `insert into kaikki_sense_keys (sense_id, orthography_insensitive_key)
     select sense_id, $2 from kaikki_senses where entry_id = $1`,
    [entryId, orthographyInsensitiveForm(form)],
  );
}

async function addWord({ wordId, displayText, syllables, definition, citeEntryId }) {
  await pool.query(
    'insert into golden_record (word_id, display_text, syllables, definition) values ($1, $2, $3, $4)',
    [wordId, displayText, syllables, definition],
  );
  if (citeEntryId) {
    const { rows } = await pool.query(
      `select etymology_number, pos, canonical_value, glosses, etymology_text
       from kaikki_senses where entry_id = $1`,
      [citeEntryId],
    );
    const s = rows[0];
    const pin = {
      etymologyNumber: s.etymology_number,
      pos: s.pos,
      canonicalForm: s.canonical_value,
      glosses: s.glosses,
      etymologyText: s.etymology_text,
    };
    await pool.query('insert into upstream_citations (word_id, entry_id, pin) values ($1, $2, $3)', [
      wordId,
      citeEntryId,
      JSON.stringify(pin),
    ]);
  }
}

function write(name, data) {
  const file = path.join(FIXTURES_DIR, name);
  writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`);
  console.log(`  wrote ${name}  (spellingVsUpstream: ${data.spellingVsUpstream}, status: ${data.status})`);
}

try {
  await cleanup();

  const { rows: userRows } = await pool.query(
    'insert into users (email, display_name, role) values ($1, $2, $3) returning user_id',
    [`${NS}curator@example.com`, 'Fixture Curator', 'curator'],
  );
  const userId = userRows[0].user_id;

  // --- cited, our spelling agrees with upstream ---------------------------
  await addSense({
    entryId: `${ENTRY_NS}adiye`,
    form: 'dùjẹ̀kù',
    pos: 'noun',
    etymologyNumber: '1',
    glosses: ['chicken', 'fowl'],
  });
  await addWord({
    wordId: `${NS}adiye_chicken`,
    displayText: 'dùjẹ̀kù',
    syllables: ['dù', 'jẹ̀', 'kù'],
    definition: 'chicken',
    citeEntryId: `${ENTRY_NS}adiye`,
  });

  // --- cited, upstream spells it differently ------------------------------
  await addSense({
    entryId: `${ENTRY_NS}kasu`,
    form: 'wòhún',
    pos: 'verb',
    etymologyNumber: '2',
    glosses: ['to fail', 'to fall short'],
  });
  await addWord({
    wordId: `${NS}kasu_fail`,
    displayText: 'wòhun',
    syllables: ['wò', 'hun'],
    definition: 'to fail',
    citeEntryId: `${ENTRY_NS}kasu`,
  });

  // --- uncited, and its spelling differs from the only candidate ----------
  await addSense({
    entryId: `${ENTRY_NS}legacy`,
    form: 'tẹ̀rùkó',
    pos: 'noun',
    etymologyNumber: '1',
    glosses: ['drum'],
  });
  await addWord({
    wordId: `${NS}ilu_drum`,
    displayText: 'tẹruko',
    syllables: ['tẹ', 'ru', 'ko'],
    definition: 'drum',
  });

  // --- uncited, one spelling with three etymologies (the `kọ́` case) -------
  for (const [n, pos, gloss] of [
    ['2', 'verb', 'to build, construct'],
    ['3', 'particle', 'a negation particle'],
    ['4', 'verb', 'to hang, suspend'],
  ]) {
    await addSense({
      entryId: `${ENTRY_NS}ko${n}`,
      form: 'gbẹ̀dùjó',
      pos,
      etymologyNumber: n,
      glosses: [gloss],
    });
  }
  await addWord({
    wordId: `${NS}ko_something`,
    displayText: 'gbẹ̀dùjó',
    syllables: ['gbẹ̀', 'dù', 'jó'],
    definition: null,
  });

  console.log('Calling the real getEntryReview handler:');
  write('entryReview.json', await getEntryReview(pool, `${NS}adiye_chicken`, userId));
  write('entryReviewCitedDiffers.json', await getEntryReview(pool, `${NS}kasu_fail`, userId));
  write('entryReviewUncited.json', await getEntryReview(pool, `${NS}ilu_drum`, userId));
  write('entryReviewAmbiguous.json', await getEntryReview(pool, `${NS}ko_something`, userId));
} finally {
  await cleanup();
  await pool.end();
}
